server:
  port: 8090



spring:
  application:
    name: wine-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1811b-four/springcloud-wine-config.git
          search-paths:  /
          username: qilong666
          password: long931010
      label: master


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
